name: loggo
description: Colorful, compact, production-friendly logging for Flutter & Dart.
version: 0.1.0
homepage: https://github.com/getme/loggo
repository: https://github.com/getme/loggo
issue_tracker: https://github.com/getme/loggo/issues

topics:
  - cli
  - logging

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
